{"cells":[{"cell_type":"code","metadata":{"tags":[],"cell_id":"c6aed90b-307f-423e-9466-8a6bab103bd5"},"source":"# standard imports\nimport json\nfrom pathlib import Path\nfrom itertools import chain\n\n# third party imports\nimport dask.bag as db\nimport dask.dataframe as dd\nimport numpy as np","outputs":[]},{"cell_type":"code","metadata":{"tags":[],"cell_id":"3e577b0c-6008-4188-bd0e-67ace3ad6c2d"},"source":"# constants\nRAW_DATA = Path('./raw_data')\nDATAFRAMES = Path('./dataframes')\nJSON_LINES = Path('./json_lines')\nALL_KEYS = Path('./all_keys/all_keys.json')","outputs":[]},{"cell_type":"code","metadata":{"tags":[],"cell_id":"5d990077-8f8b-4e21-b6f4-5f6241291c81"},"source":"# columns\ncolumns = {\n    'PageInits': ['browserRequest.browser', 'browserRequest.browserFamily',\n       'browserRequest.deviceFamily', 'browserRequest.os',\n       'browserRequest.osFamily', 'browserRequest.referrerUrl',\n       'browserRequest.screenHeight', 'browserRequest.screenPixelDepth',\n       'browserRequest.screenWidth', 'browserRequest.userAgent',\n       'campaignReferrer', 'deviceVentileGroup', 'eligiblePlacements',\n       'forceAds', 'pageId', 'pageInitializationId', 'placementTypes',\n       'productCategoryType', 'productPath', 'publisherType',\n       'publisherUserId', 'pureGroupType', 'request.buildNumber',\n       'request.requestId', 'request.requestedAt', 'segmentationType',\n       'sessionId', 'siteCountry', 'siteId', 'siteType', 'ventileGroup',\n       'webuserId'],\n    'Conversions': ['advancePurchaseRangeType', 'browserRequest.browser',\n       'browserRequest.browserFamily', 'browserRequest.deviceFamily',\n       'browserRequest.os', 'browserRequest.osFamily',\n       'browserRequest.referrerUrl', 'browserRequest.screenHeight',\n       'browserRequest.screenPixelDepth', 'browserRequest.screenWidth',\n       'browserRequest.userAgent', 'carDropoffAirportCode',\n       'carPickupAirportCode', 'conversionTransactionType', 'cookieSize',\n       'destination', 'entityId', 'isPublisherConversion',\n       'knownHotelProperty', 'orderId', 'originalConversionCurrency',\n       'origination', 'pageId', 'productCategoryType', 'publisherType',\n       'publisherUserId', 'publisherUserIdPerPub', 'request.buildNumber',\n       'request.requestId', 'request.requestedAt', 'siteId', 'siteType',\n       'thirdPartyCookieAssigned', 'thirdPartyWebuserId', 'travelDateEnd',\n       'travelDateStart', 'travelers', 'tripType'],\n    'ClientSideInfos': ['browserRequest.browser', 'browserRequest.browserFamily',\n       'browserRequest.deviceFamily', 'browserRequest.os',\n       'browserRequest.osFamily', 'browserRequest.referrerUrl',\n       'browserRequest.userAgent', 'clientId', 'clientTime',\n       'customDimensions.clickTarget', 'customDimensions.documentHeight',\n       'customDimensions.documentWidth', 'customDimensions.label',\n       'customDimensions.pageX', 'customDimensions.pageY',\n       'customDimensions.selector', 'customDimensions.viewportHeight',\n       'customDimensions.viewportWidth', 'name', 'pageId',\n       'pageInitializationId', 'publisherType', 'publisherUserId',\n       'request.requestId', 'request.requestedAt', 'siteType']\n}","outputs":[]},{"cell_type":"code","metadata":{"tags":[],"cell_id":"e7f2b20a-5453-4baf-b24d-75bf2de1053f"},"source":"DROP_COLUMNS = {\n    'PageInits': ['browserRequest.browser', 'browserRequest.browserFamily', 'browserRequest.deviceFamily', 'browserRequest.os',\n       'browserRequest.osFamily', 'browserRequest.referrerUrl', 'browserRequest.userAgent', 'eligiblePlacements', 'forceAds',\n       'placementTypes', 'publisherType', 'pureGroupType', 'request.buildNumber', 'request.requestId', 'sessionId', 'siteCountry', \n       'siteId', 'siteType', 'ventileGroup', 'webuserId'],\n    'Conversions': ['browserRequest.browser', 'browserRequest.browserFamily', 'browserRequest.deviceFamily', 'browserRequest.os', \n        'browserRequest.osFamily', 'browserRequest.referrerUrl', 'browserRequest.userAgent', 'conversionTransactionType', 'knownHotelProperty',\n        'originalConversionCurrency', 'publisherType', 'publisherUserIdPerPub', 'request.buildNumber', 'siteId', 'siteType',\n        'thirdPartyCookieAssigned', 'thirdPartyWebuserId', 'isPublisherConversion'],\n    'ClientSideInfos': ['browserRequest.browser', 'browserRequest.browserFamily', 'browserRequest.deviceFamily', 'browserRequest.os',\n       'browserRequest.osFamily', 'browserRequest.referrerUrl', 'browserRequest.userAgent', 'publisherType', 'request.requestId', 'siteType']\n}","outputs":[]},{"cell_type":"code","metadata":{"tags":[],"cell_id":"1422482e-84a6-461b-91f5-da8ee412dce5"},"source":"NUMERIC_COLUMNS = {\n    'PageInits': ['browserRequest.screenHeight', 'browserRequest.screenPixelDepth', 'browserRequest.screenWidth', 'deviceVentileGroup', ],\n    'Conversions': ['browserRequest.screenHeight', 'browserRequest.screenPixelDepth', 'browserRequest.screenWidth', 'cookieSize', 'travelers'],\n    'ClientSideInfos': ['customDimensions.documentHeight', 'customDimensions.documentWidth', 'customDimensions.pageX', 'customDimensions.pageY',\n        'customDimensions.viewportHeight', 'customDimensions.viewportWidth']\n}","outputs":[]},{"cell_type":"code","metadata":{"tags":[],"cell_id":"061c457d-1969-4539-aa66-912c5c4c782d"},"source":"DATETIME_COLUMNS = {\n    'PageInits': ['request.requestedAt'],\n    'Conversions': ['request.requestedAt', 'travelDateEnd', 'travelDateStart'],\n    'ClientSideInfos': ['clientTime', 'request.requestedAt']\n}","outputs":[]},{"cell_type":"code","metadata":{"tags":[],"cell_id":"bb34c0a5-a50e-4075-a7d2-15af0563bb17"},"source":"# import json files as dask bags\nbags = {folder.name: db.read_text(f'{str(folder)}/*.json').map(json.loads) \n        for folder in JSON_LINES.glob('*')}","outputs":[]},{"cell_type":"code","metadata":{"tags":[],"cell_id":"4fff31ec-af96-4742-a061-af7f30f3ce7d"},"source":"# convert bags to dataframes\n# also drops nas\ndfs = {folder: bag.to_dataframe(meta={col: str for col in columns[folder]}).dropna()\n        for folder, bag in bags.items()}","outputs":[]},{"cell_type":"code","metadata":{"tags":[],"cell_id":"b1ebc6a8-b5d1-46a5-a85f-7344f87cf1c9"},"source":"# drop columns\ndfs = {folder: df.drop(columns=DROP_COLUMNS[folder])\n        for folder, df in dfs.items()}","outputs":[]},{"cell_type":"code","metadata":{"tags":[],"cell_id":"01ded37e-23af-46d1-8e80-249995483b54"},"source":"# convert column types\ndfs = {folder: df.astype({col: int for col in NUMERIC_COLUMNS[folder]})\n        for folder, df in dfs.items()}","outputs":[]},{"cell_type":"code","metadata":{"tags":[],"cell_id":"bfc16378-5134-4a67-ac8b-9265c6133540"},"source":"# convert date columns\ndef convert_to_date_columns(df, columns):\n    for col in columns:\n        df[col] = dd.to_datetime(df[col])\n    return df\n\ndfs = {folder: convert_to_date_columns(df, DATETIME_COLUMNS[folder])\n        for folder, df in dfs.items()}","outputs":[]},{"cell_type":"code","source":"","metadata":{"tags":[],"cell_id":"7a578755-8b74-4182-87db-2a88edbd6676"},"outputs":[],"execution_count":null},{"cell_type":"code","metadata":{"tags":[],"cell_id":"0c4a806b-af9b-40fe-a0b2-fdd1796f823f"},"source":"# export to hdf file\nfor folder, df in dfs.items():\n    df.to_hdf(f'{str(DATAFRAMES)}/{folder}.hdf', key='df-*')","outputs":[{"name":"stderr","text":"  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-07'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-05'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-06'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-05'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-08'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-05'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-06'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-05'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-07'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-05'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-06'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-05'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-04'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-03'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-02'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-01'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-00'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n/opt/venv/lib/python3.7/site-packages/tables/path.py:155: NaturalNameWarning: object name is not a valid Python identifier: 'df-97'; it does not match the pattern ``^[a-zA-Z_][a-zA-Z0-9_]*$``; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n`; you will not be able to use natural naming to access this object; using ``getattr()`` will still work, though\n  check_attribute_name(name)\n","output_type":"stream","truncated":true}]}],"nbformat":4,"nbformat_minor":2,"metadata":{"orig_nbformat":2,"deepnote_notebook_id":"62869d7a-5a10-474c-8314-02806a0f967d","deepnote_execution_queue":[]}}